### ISSUE TITLE
Erro ao criar pagamento

### ISSUE THREAD

**Issue by zoedsoupe** [murilo-campaner/juno-nodejs#5]
Estou utilizando a biblioteca de vocês no meu servidor Node, aliás, muito obrigado, foi um achado, porém estou tendo um problema ao criar o pagamento.

ess é a função que estou utilizando:
```ts
  async createCardHash(
    data: Pick<ICreateOrderDTO, 'payment'>
  ): Promise<string> {
    const publicToken = process.env.PUBLIC_TOKEN ?? 'public-token';
    const environment = 'sandbox';

    const card = data.payment.card_number.replace(/[.-\s]/g, '');

    console.log(card);

    const cardData = {
      holderName: data.payment.holder,
      cardNumber: card,
      securityCode: data.payment.cvv,
      expirationMonth: data.payment.exp_date.slice(0, 2),
      expirationYear: data.payment.exp_date.slice(3, 7),
    };

    const junoService = new JunoCardHash(publicToken, environment);

    const hash = await junoService.getCardHash(cardData);

    return hash;
  }
```

O hash é criado com sucesso, só que ao mandar ele pra API da Juno, esse erro é retornado:
```json
{
  "timestamp": "2020-09-28T14:14:23.186-03:00",
  "status": 400,
  "error": "Bad Request",
  "details": [
    {
      "message": "Não foi possível localizar os dados do cartão de crédito a partir do hash especificado",
      "errorCode": "501008"
    }
  ],
  "path": "/payments"
}
```

Alguma ideia do que poderia ser?

**Comment by zoedsoupe** [comment]
Acabei percebendo que a biblioteca, obviamente não suporta os cartões de teste. Utilizei um pessoal e funcionou.

**Comment by murilo-campaner** [comment]
Olá @Mdsp9070 !

Então, a principio, toda essa biblioteca foi desenvolvida pra v1  da API da Juno (que funciona normalmente até o momento).
Se não me engano, os cartões de teste são utilizados apenas na v2 da API deles.

Mas que bom que deu certo!
